name: Check Website and Send Email

on:
  push:
    branches: 
      - main
  schedule:
    - cron: "0 9,21 * * *" #Runs at 9 AM & 9 PM UTC

jobs:
  check_site:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set Up Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      
      - name: Build
        run: cargo build --release

      - name: Run Script
        env:
          JOB_ID: ${{secrets.JOB_ID}}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: cargo run --bin optum-job-finder
